### ISSUE TITLE
URL bar icons too wide

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#5]
![Incorrect URL bar button width](https://user-images.githubusercontent.com/52195359/67928300-ca94c580-fc0e-11e9-85f2-e9135fa963de.png)

It's actually just the *-button-animatable-box that inherits the same width as the image, causing it to appear twice as wide.

```css
#pocket-button-animatable-box,
#star-button-animatable-box {
    display: none;
}
```

This is a quick and hacky fix, but I haven't tested to see if this breaks anything else. I'll test more when I'm home :)
