### ISSUE TITLE
Extension menus unable to open from icon in the nav-bar

### ISSUE THREAD

**Issue by diedummydie** [diedummydie/Safari-Theme-for-Firefox#9]
Clicking an extension's button in the nav-bar briefly displays an empty menu which quickly vanishes. Those same extensions will correctly display their menus if selected from the overflow menu instead.

**Comment by clo4** [comment]
Is this what the issue is referring to?

![Extension menu not showing, using userChrome CSS](https://user-images.githubusercontent.com/52195359/68080326-36fd0800-fe4d-11e9-98a1-9ccdc5fd2046.png)

As far as I can tell, it's due to something else with the profile, not the CSS. Same happens with no customizations applied.

![Extension menu not showing, no userChrome CSS](https://user-images.githubusercontent.com/52195359/68080336-6dd31e00-fe4d-11e9-939e-0c74308be5ff.png)

Using a different profile gets around the issue, *but* I also can't figure out what causes it and why it starts again after a while.

If this isn't what this issue is referring to, would you mind giving an example? 🙂

**Comment by diedummydie** [comment]
That is the issue. The empty UI popups aren't disappearing now, but the menu is still empty.

No effect: deleting all `extension*` files and `addons.json` in the profile root.

Setting `min-width` and `min-height` works, but everything else below has no effect.

```css

.PanelUI-subView {
  width:min-content!important;
  height:  unset!important;
  overflow:visible!important;
  overflow:visible!important;
  overflow-x:visible!important;
  overflow-y:visible!important;
  max-height: unset!important;
  max-width: unset!important;
  max-width:min-content!important;
  width:min-content!important;
  width:max-content!important;
  width:100%!important;
  height: auto!important;
  -moz-stack-sizing:enabled!important;

  min-width:276px!important;
  min-height: 400px!important;
  border:4px solid red!important;
}
.panel-viewcontainer {
   overflow: auto;
  width:auto!important;
  height: auto!important;
  border:4px solid blue!important;
 }

#PanelUI-multiView > .panel-viewcontainer > .panel-viewstack {
  max-width: 500!important;
}
#PanelUI-contents-scroller {
  width:800px!important;
}
```

The problem doesn't exist in other profiles, like you found, even with all of the same CSS.  

Still looking...
